/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    NButton: typeof import('naive-ui')['NButton']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NResult: typeof import('naive-ui')['NResult']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

// For TSX support
declare global {
  const AnimatePresence: (typeof import('motion-v'))['AnimatePresence']
  const NButton: (typeof import('naive-ui'))['NButton']
  const NEmpty: (typeof import('naive-ui'))['NEmpty']
  const NIcon: (typeof import('naive-ui'))['NIcon']
  const NResult: (typeof import('naive-ui'))['NResult']
  const NVirtualList: (typeof import('naive-ui'))['NVirtualList']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const VanFloatingPanel: (typeof import('vant/es'))['FloatingPanel']
  const VanIcon: (typeof import('vant/es'))['Icon']
  const VanLoading: (typeof import('vant/es'))['Loading']
  const VanOverlay: (typeof import('vant/es'))['Overlay']
  const VanPopup: (typeof import('vant/es'))['Popup']
  const VanPullRefresh: (typeof import('vant/es'))['PullRefresh']
  const VanTab: (typeof import('vant/es'))['Tab']
  const VanTabs: (typeof import('vant/es'))['Tabs']
}